version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
#    command: mongod mongod --logpath /var/logs
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - great

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    networks:
      - great
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
    environment:
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
    volumes:
      - rabbitmq-data:/data/mq
    networks:
      - great


networks:
  great:

volumes:
  keycloak-data:
  goreit-postgres-data:
  rabbitmq-data:
  mongodb-data: